# Generated by Django 5.1.4 on 2024-12-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('color', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=511, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=63)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.linemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2047)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo_url', models.CharField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.stationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.usermodel')),
            ],
        ),
    ]
