# Generated by Django 5.1.4 on 2024-12-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_linemodel_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemodel',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='name',
            field=models.CharField(default='', max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('station', models.CharField(max_length=63)),
                ('text', models.CharField(max_length=2047)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.usermodel')),
            ],
        ),
    ]
