# Generated by Django 5.1.4 on 2024-12-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_adding_lines_and_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
